# Generated by Django 4.0.1 on 2022-01-08 19:24

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('assigned_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_variant_attributes', to='product.assignedvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='image_gallery', verbose_name='Image', width_field='width')),
                ('height', models.PositiveIntegerField(blank=True, default=400, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, default=400, null=True, verbose_name='Image Width')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.variant')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedVariantAttributeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='image_gallery', verbose_name='Image', width_field='width')),
                ('height', models.PositiveIntegerField(blank=True, default=400, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, default=400, null=True, verbose_name='Image Width')),
                ('assigned_variant_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_variant_attribute_images', to='product.assignedvariantattribute')),
            ],
        ),
        migrations.AddField(
            model_name='assignedvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_variants', to='product.product'),
        ),
        migrations.AddField(
            model_name='assignedvariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_product_variants', to='product.variant'),
        ),
    ]
