# Generated by Django 4.0.1 on 2022-01-08 19:36

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedvariantattributeimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='image_gallery/', verbose_name='Image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='image_gallery/', verbose_name='Image', width_field='width'),
        ),
    ]
